### ISSUE TITLE
Don't use yet?

### ISSUE THREAD

**Issue by kenetik** [mattes/wp-cli-quick-command#1]
You've got a huge comment suggesting not to use yet, why? 

What needs work?

**Comment by mattes** [comment]
The plugin is not working at all, see https://github.com/mattes/wp-cli-quick-install-command/blob/master/wp-cli-quick-install-command.php ;-) No content at all. I will continue working on this plugin soon.

**Comment by mattes** [comment]
Should be working now. Please submit bugs!
